return {
	"How to use the text-to-speech software [Voicevox]",
	"And how to Use the game engine [Defold]",
	"For make a Zundamon talk show app",
	"First, set up VoiceVox ",
	"Select [Option] from [Settings]",
	"Check [Export lab file]",
	"And check [Export txt file]",
	"[Output file name pattern] rewrite [zunda]",
	"Write her speak in [Voice Vox]",
	"Select [Export audio] from [File]",
	"[txt], [wav], and [lab] files were output to the folder",
	"Now it's Defold turn",
	"Open this sample project in Defold",
	"Drag and drop txt, wav, and lab files",
	"to the Defold editor",
	"[txt files] are in the text folder",
	"[wav files] are in the sound folder",
	"[lab files] are in the Lips folder",
	"This sample project cannot read those files",
	"So convert those to a Lua file and game object",
	"Multiple selected lab files",
	"And right-click",
	"And press [create table from lab]",
	"Result, [lips.lua file ] will be created",
	"Similarly, Multiple selected and right-click action",
	"[Text Lua files] will be created",
	"Multiple selected and right-click action",
	"[sound game object] will be created",
	"All set!",
	"Are Lua files and sound game object addresss correct?",
	"If you are not mistaken, it should work",
	"Press [Build] from [Project]",
	"I did it! Zundamon was able to talk!",
	"In this sample project,",
	"I tried only making Zundamon talk show",
	"But, Defold has various uses.",
	"Change assets and slideshow",
	"Or rewrite speak,or add script",
	"End ."
}
